In [21]:
import numpy as np
import pandas as pd

In [103]:
import os
# os.getcwd()

In [27]:
df = pd.read_csv("..\Data\car_fuel_efficiency_2026.csv")

In [30]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [29]:
len(df)

10000

In [32]:
df["fuel_type"].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [35]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [55]:
count = 0
for col in df.columns:
    count += bool(df[col].isna().sum())

In [56]:
count

2

In [57]:
df_Asia = df["origin"] == "Asia"

In [60]:
df[df_Asia].fuel_efficiency_mpg.max()

np.float64(41.2)

In [61]:
df["horsepower"].median()

np.float64(254.0)

In [64]:
freq = df["horsepower"].mode()[0]

In [65]:
df["horsepower"] = df["horsepower"].fillna(freq)

In [66]:
df["horsepower"].median()

np.float64(252.0)

In [67]:
df_car_Asia = df[df_Asia]

In [88]:
 x = df_car_Asia[["vehicle_weight", "model_year"]].head(7)

In [89]:
type(x)

pandas.DataFrame

In [90]:
x = x.values

In [91]:
type(x)

numpy.ndarray

In [92]:
x

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [95]:
xtx = x.T @ x

In [96]:
xtx_inv = np.linalg.inv(xtx)

In [97]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [98]:
interm = xtx_inv @ x.T

In [99]:
interm

array([[-2.50082897e-04, -1.65786806e-05, -2.86196661e-04,
         3.99964853e-04, -1.18162927e-03,  1.10298508e-03,
         2.25354894e-04],
       [ 6.12974614e-04,  1.06954785e-04,  6.91249245e-04,
        -7.95968736e-04,  2.63152339e-03, -2.31749941e-03,
        -4.16221392e-04]])

In [100]:
w = interm @ y

In [101]:
w

array([0.13644777, 0.2327492 ])

In [102]:
sum(w)

np.float64(0.36919696904925486)